// This file is released under the 3-clause BSD license. See COPYING-BSD.
// Generated by builder.sce : Please, do not edit this file
// cleaner.sce
// ------------------------------------------------------
curdir = pwd();
cleaner_path = get_file_path('cleaner.sce');
chdir(cleaner_path);
// ------------------------------------------------------
if fileinfo('loader.sce') <> [] then
  mdelete('loader.sce');
end
// ------------------------------------------------------
if fileinfo('libFOSSEE_Optimization_Toolbox.so') <> [] then
  mdelete('libFOSSEE_Optimization_Toolbox.so');
end
// ------------------------------------------------------
if fileinfo('libFOSSEE_Optimization_Toolbox.cpp') <> [] then
  mdelete('libFOSSEE_Optimization_Toolbox.cpp');
end
// ------------------------------------------------------
if fileinfo('libFOSSEE_Optimization_Toolbox.hxx') <> [] then
  mdelete('libFOSSEE_Optimization_Toolbox.hxx');
end
// ------------------------------------------------------
if fileinfo('libFOSSEE_Optimization_Toolbox.h') <> [] then
  mdelete('libFOSSEE_Optimization_Toolbox.h');
end
// ------------------------------------------------------
chdir(curdir);
// ------------------------------------------------------
