#ifndef __LIBFOSSEE_OPTIMIZATION_TOOLBOX_GW_H__
#define __LIBFOSSEE_OPTIMIZATION_TOOLBOX_GW_H__

#include "c_gateway_prototype.h"

STACK_GATEWAY_PROTOTYPE(sci_linearprog);
STACK_GATEWAY_PROTOTYPE(sci_rmps);

#endif /* __LIBFOSSEE_OPTIMIZATION_TOOLBOX_GW_H__ */
