#ifndef __LIBFOSSEE_OPTIMIZATION_TOOLBOX_GW_HXX__
#define __LIBFOSSEE_OPTIMIZATION_TOOLBOX_GW_HXX__

#ifdef _MSC_VER
#ifdef LIBFOSSEE_OPTIMIZATION_TOOLBOX_GW_EXPORTS
#define LIBFOSSEE_OPTIMIZATION_TOOLBOX_GW_IMPEXP __declspec(dllexport)
#else
#define LIBFOSSEE_OPTIMIZATION_TOOLBOX_GW_IMPEXP __declspec(dllimport)
#endif
#else
#define LIBFOSSEE_OPTIMIZATION_TOOLBOX_GW_IMPEXP
#endif

extern "C" LIBFOSSEE_OPTIMIZATION_TOOLBOX_GW_IMPEXP int libFOSSEE_Optimization_Toolbox(wchar_t* _pwstFuncName);



#endif /* __LIBFOSSEE_OPTIMIZATION_TOOLBOX_GW_HXX__ */
